<?php
include('system/models/About.php');
include('system/models/Cart.php');
include('system/models/Client.php');
include('system/models/Committees.php');
include('system/models/CommonQuestions.php');
include('system/models/Contact.php');
include('system/models/Directors.php');
include('system/models/Donate.php');
include('system/models/DonateType.php');
include('system/models/EventActivity.php');
include('system/models/Founders.php');
include('system/models/Magazine.php');
include('system/models/MediaCenter.php');
include('system/models/Message.php');
include('system/models/Orders.php');
include('system/models/paymentMethod.php');
include('system/models/Setting.php');
include('system/models/Slider.php');
include('system/models/User.php');
?>